### ISSUE TITLE
Impossibilité de lancer le site en local

### ISSUE THREAD

**Issue by EmmanuelDemey** [jak78/agilille-2021#14]
J'obtiens cette erreur quand je lance le server.sh. 

![image](https://user-images.githubusercontent.com/555768/154526626-2132b948-d45c-4eb7-885a-c2eb468bd994.png)

**Comment by jak78** [comment]
Merci. Je reproduis le pb, je traite le point.

**Comment by jak78** [comment]
Ca devrait être OK maintenant
